version: '3.7'

services:
  adguardhome:
    image: adguard/adguardhome:arm64-latest
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      # - "443:443"
      - "853:853"
      - "3000:3000"
    volumes:
      - "./adguardhome/work:/opt/adguardhome/work"
      - "./adguardhome/conf:/opt/adguardhome/conf"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    dns:
      - 127.0.0.1
      - 1.1.1.1

  nginx:
    depends_on:
      - homeassistant
    image: nginx
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.4
    ports:
      - "443:443"
    volumes:
      - "./nginx/etc-nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/etc-nginx-certs:/etc/nginx/certs"
    dns: 10.0.0.3

  homeassistant:
    depends_on:
      - mosquitto
    image: homeassistant/home-assistant
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.5
    ports:
      - "8123:8123"
    volumes:
      - "./homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - PYTHONWARNINGS=ignore:Unverified HTTPS request
    dns: 10.0.0.3

  mosquitto:
    depends_on:
      - adguardhome
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.6
    ports:
      - "1883:1883"
      - "9001:9001"
#    volumes:
#      - "./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
#      - "./mosquitto/config/password_file:/mosquitto/config/password_file"
#      - "./mosquitto/config/acl_file:/mosquitto/config/acl_file"
    dns: 10.0.0.3

  zigbee2mqtt:
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.7
    volumes:
      - "./zigbee2mqtt/data:/app/data"
      - "./zigbee2mqtt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters"
      - "./zigbee2mqtt/homeassistant-extension/homeassistant.js:/app/lib/extension/homeassistant.js"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    devices:
       - "/dev/ttyACM0:/dev/ttyACM0"
    dns: 10.0.0.3

  telegraf:
    depends_on:
      - adguardhome
    image: telegraf
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 10.0.0.8
    volumes:
      - "./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    dns: 10.0.0.3

networks:
  backbone:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28
